TARGET = lib_pcl_surface
TEMPLATE = lib

DEFINES += LIB_PCL_SURFACE_LIBRARY

SOURCES += src/bilateral_upsampling.cpp
SOURCES += src/concave_hull.cpp
SOURCES += src/convex_hull.cpp
SOURCES += src/ear_clipping.cpp
SOURCES += src/gp3.cpp
SOURCES += src/grid_projection.cpp
SOURCES += src/marching_cubes.cpp
SOURCES += src/marching_cubes_hoppe.cpp
SOURCES += src/marching_cubes_rbf.cpp
SOURCES += src/mls.cpp
SOURCES += src/organized_fast_mesh.cpp
SOURCES += src/poisson.cpp
SOURCES += src/processing.cpp
SOURCES += src/simplification_remove_unused_vertices.cpp
SOURCES += src/surfel_smoothing.cpp
SOURCES += src/texture_mapping.cpp

# SOURCES += src/3rdparty/opennurbs/adler32.c
# SOURCES += src/3rdparty/opennurbs/compress.c
# SOURCES += src/3rdparty/opennurbs/crc32.c
# SOURCES += src/3rdparty/opennurbs/deflate.c
# SOURCES += src/3rdparty/opennurbs/infback.c
# SOURCES += src/3rdparty/opennurbs/inffast.c
# SOURCES += src/3rdparty/opennurbs/inflate.c
# SOURCES += src/3rdparty/opennurbs/inftrees.c
# SOURCES += src/3rdparty/opennurbs/opennurbs_3dm_attributes.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_3dm_properties.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_3dm_settings.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_annotation.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_annotation2.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_arc.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_arccurve.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_archive.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_array.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_base32.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_base64.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_beam.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_bezier.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_beziervolume.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_bitmap.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_bounding_box.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_box.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_brep.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_brep_extrude.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_brep_io.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_brep_isvalid.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_brep_region.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_brep_tools.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_brep_v2valid.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_circle.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_color.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_compress.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_cone.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_crc.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_curve.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_curveonsurface.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_curveproxy.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_cylinder.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_defines.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_detail.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_dimstyle.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_dll.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_ellipse.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_embedded_file.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_error.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_error_message.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_evaluate_nurbs.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_extensions.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_font.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_fsp.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_geometry.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_gl.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_group.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_hatch.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_instance.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_intersect.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_knot.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_layer.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_light.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_line.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_linecurve.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_linetype.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_lookup.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_material.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_math.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_matrix.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_memory.c
# SOURCES += src/3rdparty/opennurbs/opennurbs_memory_util.c
# SOURCES += src/3rdparty/opennurbs/opennurbs_mesh.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_mesh_ngon.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_mesh_tools.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_morph.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_nurbscurve.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_nurbssurface.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_nurbsvolume.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_object.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_object_history.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_objref.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_offsetsurface.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_optimize.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_plane.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_planesurface.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_pluginlist.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_point.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_pointcloud.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_pointgeometry.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_pointgrid.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_polycurve.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_polyedgecurve.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_polyline.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_polylinecurve.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_precompiledheader.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_rand.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_revsurface.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_rtree.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_sort.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_sphere.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_string.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_sum.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_sumsurface.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_surface.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_surfaceproxy.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_textlog.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_torus.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_unicode.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_userdata.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_uuid.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_viewport.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_workspace.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_wstring.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_xform.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_zlib.cpp
# SOURCES += src/3rdparty/opennurbs/opennurbs_zlib_memory.cpp
# SOURCES += src/3rdparty/opennurbs/trees.c
# SOURCES += src/3rdparty/opennurbs/uncompr.c
# SOURCES += src/3rdparty/opennurbs/zutil.c

SOURCES += src/3rdparty/poisson4/bspline_data.cpp
SOURCES += src/3rdparty/poisson4/factor.cpp
SOURCES += src/3rdparty/poisson4/geometry.cpp
SOURCES += src/3rdparty/poisson4/marching_cubes_poisson.cpp

# SOURCES += src/on_nurbs/closing_boundary.cpp
# SOURCES += src/on_nurbs/fitting_curve_2d.cpp
# SOURCES += src/on_nurbs/fitting_curve_2d_apdm.cpp
# SOURCES += src/on_nurbs/fitting_curve_2d_asdm.cpp
# SOURCES += src/on_nurbs/fitting_curve_2d_atdm.cpp
# SOURCES += src/on_nurbs/fitting_curve_2d_pdm.cpp
# SOURCES += src/on_nurbs/fitting_curve_2d_sdm.cpp
# SOURCES += src/on_nurbs/fitting_curve_2d_tdm.cpp
# SOURCES += src/on_nurbs/fitting_curve_pdm.cpp
# SOURCES += src/on_nurbs/fitting_cylinder_pdm.cpp
# SOURCES += src/on_nurbs/fitting_sphere_pdm.cpp
# SOURCES += src/on_nurbs/fitting_surface_im.cpp
# SOURCES += src/on_nurbs/fitting_surface_pdm.cpp
# SOURCES += src/on_nurbs/fitting_surface_tdm.cpp
# SOURCES += src/on_nurbs/global_optimization_pdm.cpp
# SOURCES += src/on_nurbs/global_optimization_tdm.cpp
# SOURCES += src/on_nurbs/nurbs_solve_eigen.cpp
# SOURCES += src/on_nurbs/nurbs_solve_umfpack.cpp
# SOURCES += src/on_nurbs/nurbs_tools.cpp
# SOURCES += src/on_nurbs/sequential_fitter.cpp
# SOURCES += src/on_nurbs/sparse_mat.cpp
# SOURCES += src/on_nurbs/triangulation.cpp

# SOURCES += src/vtk_smoothing/vtk_mesh_quadric_decimation.cpp
# SOURCES += src/vtk_smoothing/vtk_mesh_smoothing_laplacian.cpp
# SOURCES += src/vtk_smoothing/vtk_mesh_smoothing_windowed_sinc.cpp
# SOURCES += src/vtk_smoothing/vtk_mesh_subdivision.cpp
# SOURCES += src/vtk_smoothing/vtk_utils.cpp

HEADERS += inc/pcl/surface/bilateral_upsampling.h
HEADERS += inc/pcl/surface/boost.h
HEADERS += inc/pcl/surface/concave_hull.h
HEADERS += inc/pcl/surface/convex_hull.h
HEADERS += inc/pcl/surface/ear_clipping.h
HEADERS += inc/pcl/surface/eigen.h
HEADERS += inc/pcl/surface/gp3.h
HEADERS += inc/pcl/surface/grid_projection.h
HEADERS += inc/pcl/surface/marching_cubes.h
HEADERS += inc/pcl/surface/marching_cubes_hoppe.h
HEADERS += inc/pcl/surface/marching_cubes_rbf.h
HEADERS += inc/pcl/surface/mls.h
HEADERS += inc/pcl/surface/organized_fast_mesh.h
HEADERS += inc/pcl/surface/poisson.h
HEADERS += inc/pcl/surface/processing.h
HEADERS += inc/pcl/surface/qhull.h
HEADERS += inc/pcl/surface/reconstruction.h
HEADERS += inc/pcl/surface/simplification_remove_unused_vertices.h
HEADERS += inc/pcl/surface/surfel_smoothing.h
HEADERS += inc/pcl/surface/texture_mapping.h

# HEADERS += inc/pcl/surface/3rdparty/opennurbs/crc32.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/deflate.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/examples_linking_pragmas.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/inffast.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/inffixed.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/inflate.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/inftrees.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_3dm.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_3dm_attributes.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_3dm_properties.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_3dm_settings.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_annotation.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_annotation2.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_arc.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_arccurve.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_archive.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_array.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_array_defs.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_base32.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_base64.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_beam.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_bezier.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_bitmap.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_bounding_box.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_box.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_brep.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_circle.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_color.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_compress.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_cone.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_crc.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_curve.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_curveonsurface.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_curveproxy.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_cylinder.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_defines.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_detail.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_dimstyle.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_dll_resource.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_ellipse.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_error.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_evaluate_nurbs.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_extensions.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_font.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_fpoint.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_fsp.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_fsp_defs.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_geometry.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_gl.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_group.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_hatch.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_hsort_template.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_instance.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_intersect.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_knot.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_layer.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_light.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_line.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_linecurve.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_linestyle.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_linetype.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_lookup.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_mapchan.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_material.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_math.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_matrix.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_memory.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_mesh.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_nurbscurve.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_nurbssurface.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_object.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_object_history.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_objref.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_offsetsurface.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_optimize.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_plane.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_planesurface.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_pluginlist.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_point.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_pointcloud.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_pointgeometry.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_pointgrid.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_polycurve.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_polyedgecurve.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_polyline.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_polylinecurve.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_qsort_template.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_rand.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_rendering.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_revsurface.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_rtree.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_sphere.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_string.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_sumsurface.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_surface.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_surfaceproxy.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_system.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_textlog.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_texture.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_texture_mapping.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_torus.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_unicode.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_userdata.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_uuid.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_version.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_viewport.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_workspace.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_xform.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/opennurbs_zlib.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/trees.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/zconf.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/zlib.h
# HEADERS += inc/pcl/surface/3rdparty/opennurbs/zutil.h

HEADERS += inc/pcl/surface/3rdparty/poisson4/allocator.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/binary_node.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/bspline_data.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/bspline_data.hpp
HEADERS += inc/pcl/surface/3rdparty/poisson4/factor.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/function_data.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/function_data.hpp
HEADERS += inc/pcl/surface/3rdparty/poisson4/geometry.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/geometry.hpp
HEADERS += inc/pcl/surface/3rdparty/poisson4/marching_cubes_poisson.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/mat.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/mat.hpp
HEADERS += inc/pcl/surface/3rdparty/poisson4/multi_grid_octree_data.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/multi_grid_octree_data.hpp
HEADERS += inc/pcl/surface/3rdparty/poisson4/octree_poisson.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/octree_poisson.hpp
HEADERS += inc/pcl/surface/3rdparty/poisson4/poisson_exceptions.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/polynomial.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/polynomial.hpp
HEADERS += inc/pcl/surface/3rdparty/poisson4/ppolynomial.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/ppolynomial.hpp
HEADERS += inc/pcl/surface/3rdparty/poisson4/sparse_matrix.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/sparse_matrix.hpp
HEADERS += inc/pcl/surface/3rdparty/poisson4/vector.h
HEADERS += inc/pcl/surface/3rdparty/poisson4/vector.hpp

HEADERS += inc/pcl/surface/impl/bilateral_upsampling.hpp
HEADERS += inc/pcl/surface/impl/concave_hull.hpp
HEADERS += inc/pcl/surface/impl/convex_hull.hpp
HEADERS += inc/pcl/surface/impl/gp3.hpp
HEADERS += inc/pcl/surface/impl/grid_projection.hpp
HEADERS += inc/pcl/surface/impl/marching_cubes.hpp
HEADERS += inc/pcl/surface/impl/marching_cubes_hoppe.hpp
HEADERS += inc/pcl/surface/impl/marching_cubes_rbf.hpp
HEADERS += inc/pcl/surface/impl/mls.hpp
HEADERS += inc/pcl/surface/impl/organized_fast_mesh.hpp
HEADERS += inc/pcl/surface/impl/poisson.hpp
HEADERS += inc/pcl/surface/impl/processing.hpp
HEADERS += inc/pcl/surface/impl/reconstruction.hpp
HEADERS += inc/pcl/surface/impl/surfel_smoothing.hpp
HEADERS += inc/pcl/surface/impl/texture_mapping.hpp

# HEADERS += inc/pcl/surface/on_nurbs/closing_boundary.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_curve_2d.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_curve_2d_apdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_curve_2d_asdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_curve_2d_atdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_curve_2d_pdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_curve_2d_sdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_curve_2d_tdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_curve_pdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_cylinder_pdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_sphere_pdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_surface_im.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_surface_pdm.h
# HEADERS += inc/pcl/surface/on_nurbs/fitting_surface_tdm.h
# HEADERS += inc/pcl/surface/on_nurbs/global_optimization_pdm.h
# HEADERS += inc/pcl/surface/on_nurbs/global_optimization_tdm.h
# HEADERS += inc/pcl/surface/on_nurbs/nurbs_data.h
# HEADERS += inc/pcl/surface/on_nurbs/nurbs_solve.h
# HEADERS += inc/pcl/surface/on_nurbs/nurbs_tools.h
# HEADERS += inc/pcl/surface/on_nurbs/sequential_fitter.h
# HEADERS += inc/pcl/surface/on_nurbs/sparse_mat.h
# HEADERS += inc/pcl/surface/on_nurbs/triangulation.h

# HEADERS += inc/pcl/surface/vtk_smoothing/vtk.h
# HEADERS += inc/pcl/surface/vtk_smoothing/vtk_mesh_quadric_decimation.h
# HEADERS += inc/pcl/surface/vtk_smoothing/vtk_mesh_smoothing_laplacian.h
# HEADERS += inc/pcl/surface/vtk_smoothing/vtk_mesh_smoothing_windowed_sinc.h
# HEADERS += inc/pcl/surface/vtk_smoothing/vtk_mesh_subdivision.h
# HEADERS += inc/pcl/surface/vtk_smoothing/vtk_utils.h

